# Generated by Django 4.2.16 on 2024-11-08 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_alter_event_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_range',
            field=models.IntegerField(choices=[(0, 'newborns'), (1, '0-12 months'), (2, '2-3 years'), (3, '4-5 years'), (4, '5-8 years'), (5, '8-12 years'), (6, '13+'), (7, 'All ages')], default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='event.event')),
            ],
        ),
    ]
