# Generated by Django 4.2.16 on 2024-11-13 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbs_down',
            field=models.ManyToManyField(related_name='event_thumbs_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbs_up',
            field=models.ManyToManyField(related_name='event_thumbs_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
