# Generated by Django 4.2.16 on 2024-11-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_event_thumbs_down_remove_event_thumbs_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='excerpt',
        ),
    ]
